parser: 'babel-eslint'
env:
  browser: true
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: 'airbnb'
plugins:
 - mocha
 - promise
rules:
  no-console: off
  strict: off
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
